name: docsify-action docs

on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/docsify-action@master
      with:
          # github access token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # destination dir
          dir: app/
          # destination branch
          branch: prod
